# Generated by Django 5.2.9 on 2025-12-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_user_email_change_code_user_email_change_new_email_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_change_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_change_new_email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_change_requested_at",
        ),
    ]
