# Generated by Django 5.2.9 on 2025-12-09 13:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Lowercase alphanumeric with hyphens, no spaces",
                        max_length=150,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Name must be lowercase alphanumeric with hyphens only, no spaces.",
                                regex="^[a-z0-9-]+$",
                            )
                        ],
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("is_official", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "repositories",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "name"), name="unique_owner_name"
                    )
                ],
            },
        ),
    ]
