# Generated by Django 5.2.9 on 2025-12-09 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="is_public",
        ),
        migrations.AddField(
            model_name="repository",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")], default="PUBLIC"
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="name",
            field=models.CharField(
                help_text="Lowercase alphanumeric with hyphens, no spaces",
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name is lowercase alphanumeric with hyphens, no spaces.",
                        regex="^[a-z0-9-]+$",
                    )
                ],
            ),
        ),
    ]
