# Generated by Django 5.2.9 on 2025-12-16 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0003_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_official", True)),
                fields=("name",),
                name="unique_official_repo_name",
            ),
        ),
    ]
