# Generated by Django 5.2.9 on 2025-12-16 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0004_repository_unique_official_repo_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="repository",
            name="unique_owner_name",
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_official", False)),
                fields=("owner", "name"),
                name="unique_owner_name",
            ),
        ),
    ]
