# Generated by Django 5.2.9 on 2025-12-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0005_remove_repository_unique_owner_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="digest",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="size",
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
