# Generated by Django 5.2.9 on 2025-12-27 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0006_alter_tag_digest_alter_tag_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="arch",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="tag",
            name="image_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="tag",
            name="last_synced",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="tag",
            name="os",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
