# Generated by Django 5.2.9 on 2025-12-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0007_tag_arch_tag_image_type_tag_last_synced_tag_os"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="repository",
            table="repositories",
        ),
    ]
