# Generated by Django 5.2.10 on 2026-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0009_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='star_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
